openapi: 3.0.0
info:
  title: Node.js DynamoDB Server API
  version: 1.0.0
tags:
  - name: auth
    description: Authentication related operations (login, register, etc.)
  - name: user
    description: User related operations (update, delete, etc.)
paths:
  # Auth routes
  /api/auth/register:
    post:
      tags: 
        - auth
      summary: Register a new user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profilePicture:
                  type: string
                  format: binary
                pdf:
                  type: string
                  format: binary
      responses:
        '201':
          description: User registered successfully

  /api/auth/login:
    post:
      tags: 
        - auth
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully

  /api/auth/forgot-password:
    post:
      tags: 
        - auth
      summary: Request password reset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset email sent

  /api/auth/reset-password:
    post:
      tags: 
        - auth
      summary: Reset password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resetToken:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successfully
        '400':
          description: Missing reset token or new password
        '500':
          description: Internal Server Error

  # User routes
  /api/user/update:
    put:
      tags: 
        - user
      summary: Update user details
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User updated successfully

  /api/user/delete:
    delete:
      tags: 
        - user
      summary: Delete user account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User deleted successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
